# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\code\python\Authenticate\main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from Ui_select import Ui_Dialog
from myDialog import myDialog
from myLabel import myLabel
from constant import NAME, NAME_DIC


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1172, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.l_img_1_1 = myLabel(self.centralwidget)
        self.l_img_1_1.setGeometry(QtCore.QRect(20, 20, 101, 101))
        self.l_img_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_1_1.setObjectName("l_img_1_1")
        self.l_aut_1_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_1_1.setEnabled(False)
        self.l_aut_1_1.setGeometry(QtCore.QRect(130, 20, 101, 101))
        self.l_aut_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_1_1.setObjectName("l_aut_1_1")
        self.b_buy_1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_1_1.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.b_buy_1_1.setObjectName("b_buy_1_1")
        self.b_aut_1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_1_1.setEnabled(False)
        self.b_aut_1_1.setGeometry(QtCore.QRect(130, 130, 101, 31))
        self.b_aut_1_1.setObjectName("b_aut_1_1")

        self.l_img_1_2 = myLabel(self.centralwidget)
        self.l_img_1_2.setGeometry(QtCore.QRect(250, 20, 101, 101))
        self.l_img_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_1_2.setObjectName("l_img_1_2")
        self.l_aut_1_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_1_2.setEnabled(False)
        self.l_aut_1_2.setGeometry(QtCore.QRect(360, 20, 101, 101))
        self.l_aut_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_1_2.setObjectName("l_aut_1_2")
        self.b_buy_1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_1_2.setGeometry(QtCore.QRect(250, 130, 101, 31))
        self.b_buy_1_2.setObjectName("b_buy_1_2")
        self.b_aut_1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_1_2.setEnabled(False)
        self.b_aut_1_2.setGeometry(QtCore.QRect(360, 130, 101, 31))
        self.b_aut_1_2.setObjectName("b_aut_1_2")
        
        self.l_img_1_3 = myLabel(self.centralwidget)
        self.l_img_1_3.setGeometry(QtCore.QRect(480, 20, 101, 101))
        self.l_img_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_1_3.setObjectName("l_img_1_3")
        self.l_aut_1_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_1_3.setEnabled(False)
        self.l_aut_1_3.setGeometry(QtCore.QRect(590, 20, 101, 101))
        self.l_aut_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_1_3.setObjectName("l_aut_1_3")
        self.b_buy_1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_1_3.setGeometry(QtCore.QRect(480, 130, 101, 31))
        self.b_buy_1_3.setObjectName("b_buy_1_3")
        self.b_aut_1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_1_3.setEnabled(False)
        self.b_aut_1_3.setGeometry(QtCore.QRect(590, 130, 101, 31))
        self.b_aut_1_3.setObjectName("b_aut_1_3")
        
        self.l_img_1_4 = myLabel(self.centralwidget)
        self.l_img_1_4.setGeometry(QtCore.QRect(710, 20, 101, 101))
        self.l_img_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_1_4.setObjectName("l_img_1_4")
        self.l_aut_1_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_1_4.setEnabled(False)
        self.l_aut_1_4.setGeometry(QtCore.QRect(820, 20, 101, 101))
        self.l_aut_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_1_4.setObjectName("l_aut_1_4")
        self.b_buy_1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_1_4.setGeometry(QtCore.QRect(710, 130, 101, 31))
        self.b_buy_1_4.setObjectName("b_buy_1_4")
        self.b_aut_1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_1_4.setEnabled(False)
        self.b_aut_1_4.setGeometry(QtCore.QRect(820, 130, 101, 31))
        self.b_aut_1_4.setObjectName("b_aut_1_4")

        self.l_img_1_5 = myLabel(self.centralwidget)
        self.l_img_1_5.setGeometry(QtCore.QRect(940, 20, 101, 101))
        self.l_img_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_1_5.setObjectName("l_img_1_5")
        self.l_aut_1_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_1_5.setEnabled(False)
        self.l_aut_1_5.setGeometry(QtCore.QRect(1050, 20, 101, 101))
        self.l_aut_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_1_5.setObjectName("l_aut_1_5")
        self.b_buy_1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_1_5.setGeometry(QtCore.QRect(940, 130, 101, 31))
        self.b_buy_1_5.setObjectName("b_buy_1_5")
        self.b_aut_1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_1_5.setEnabled(False)
        self.b_aut_1_5.setGeometry(QtCore.QRect(1050, 130, 101, 31))
        self.b_aut_1_5.setObjectName("b_aut_1_5")

        self.l_img_2_1 = myLabel(self.centralwidget)
        self.l_img_2_1.setGeometry(QtCore.QRect(20, 170, 101, 101))
        self.l_img_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_2_1.setObjectName("l_img_2_1")
        self.l_aut_2_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_2_1.setEnabled(False)
        self.l_aut_2_1.setGeometry(QtCore.QRect(130, 170, 101, 101))
        self.l_aut_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_2_1.setObjectName("l_aut_2_1")
        self.b_buy_2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_2_1.setGeometry(QtCore.QRect(20, 280, 101, 31))
        self.b_buy_2_1.setObjectName("b_buy_2_1")
        self.b_aut_2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_2_1.setEnabled(False)
        self.b_aut_2_1.setGeometry(QtCore.QRect(130, 280, 101, 31))
        self.b_aut_2_1.setObjectName("b_aut_2_1")
                        
        self.l_img_2_2 = myLabel(self.centralwidget)
        self.l_img_2_2.setGeometry(QtCore.QRect(250, 170, 101, 101))
        self.l_img_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_2_2.setObjectName("l_img_2_2")
        self.l_aut_2_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_2_2.setEnabled(False)
        self.l_aut_2_2.setGeometry(QtCore.QRect(360, 170, 101, 101))
        self.l_aut_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_2_2.setObjectName("l_aut_2_2")
        self.b_buy_2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_2_2.setGeometry(QtCore.QRect(250, 280, 101, 31))
        self.b_buy_2_2.setObjectName("b_buy_2_2")
        self.b_aut_2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_2_2.setEnabled(False)
        self.b_aut_2_2.setGeometry(QtCore.QRect(360, 280, 101, 31))
        self.b_aut_2_2.setObjectName("b_aut_2_2")
                
        self.l_img_2_3 = myLabel(self.centralwidget)
        self.l_img_2_3.setGeometry(QtCore.QRect(480, 170, 101, 101))
        self.l_img_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_2_3.setObjectName("l_img_2_3")
        self.l_aut_2_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_2_3.setEnabled(False)
        self.l_aut_2_3.setGeometry(QtCore.QRect(590, 170, 101, 101))
        self.l_aut_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_2_3.setObjectName("l_aut_2_3")
        self.b_buy_2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_2_3.setGeometry(QtCore.QRect(480, 280, 101, 31))
        self.b_buy_2_3.setObjectName("b_buy_2_3")
        self.l_img_2_5 = myLabel(self.centralwidget)
        self.l_img_2_5.setGeometry(QtCore.QRect(940, 170, 101, 101))
        self.l_img_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_2_5.setObjectName("l_img_2_5")
        self.l_aut_2_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_2_5.setEnabled(False)
        self.l_aut_2_5.setGeometry(QtCore.QRect(1050, 170, 101, 101))
        self.l_aut_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_2_5.setObjectName("l_aut_2_5")
        self.b_aut_2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_2_3.setEnabled(False)
        self.b_aut_2_3.setGeometry(QtCore.QRect(590, 280, 101, 31))
        self.b_aut_2_3.setObjectName("b_aut_2_3")

        self.l_img_2_4 = myLabel(self.centralwidget)
        self.l_img_2_4.setGeometry(QtCore.QRect(710, 170, 101, 101))
        self.l_img_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_2_4.setObjectName("l_img_2_4")
        self.l_aut_2_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_2_4.setEnabled(False)
        self.l_aut_2_4.setGeometry(QtCore.QRect(820, 170, 101, 101))
        self.l_aut_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_2_4.setObjectName("l_aut_2_4")
        self.b_buy_2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_2_4.setGeometry(QtCore.QRect(710, 280, 101, 31))
        self.b_buy_2_4.setObjectName("b_buy_2_4")
        self.b_aut_2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_2_4.setEnabled(False)
        self.b_aut_2_4.setGeometry(QtCore.QRect(820, 280, 101, 31))
        self.b_aut_2_4.setObjectName("b_aut_2_4")
        
        self.b_buy_2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_2_5.setGeometry(QtCore.QRect(940, 280, 101, 31))
        self.b_buy_2_5.setObjectName("b_buy_2_5")
        self.b_aut_2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_2_5.setEnabled(False)
        self.b_aut_2_5.setGeometry(QtCore.QRect(1050, 280, 101, 31))
        self.b_aut_2_5.setObjectName("b_aut_2_5")

        self.l_img_3_1 = myLabel(self.centralwidget)
        self.l_img_3_1.setGeometry(QtCore.QRect(20, 320, 101, 101))
        self.l_img_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_3_1.setObjectName("l_img_3_1")
        self.l_aut_3_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_3_1.setEnabled(False)
        self.l_aut_3_1.setGeometry(QtCore.QRect(130, 320, 101, 101))
        self.l_aut_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_3_1.setObjectName("l_aut_3_1")
        self.b_buy_3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_3_1.setGeometry(QtCore.QRect(20, 430, 101, 31))
        self.b_buy_3_1.setObjectName("b_buy_3_1")
        self.b_aut_3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_3_1.setEnabled(False)
        self.b_aut_3_1.setGeometry(QtCore.QRect(130, 430, 101, 31))
        self.b_aut_3_1.setObjectName("b_aut_3_1")
        
        self.l_img_3_2 = myLabel(self.centralwidget)
        self.l_img_3_2.setGeometry(QtCore.QRect(250, 320, 101, 101))
        self.l_img_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_3_2.setObjectName("l_img_3_2")
        self.l_aut_3_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_3_2.setEnabled(False)
        self.l_aut_3_2.setGeometry(QtCore.QRect(360, 320, 101, 101))
        self.l_aut_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_3_2.setObjectName("l_aut_3_2")
        self.b_buy_3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_3_2.setGeometry(QtCore.QRect(250, 430, 101, 31))
        self.b_buy_3_2.setObjectName("b_buy_3_2")
        self.b_aut_3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_3_2.setEnabled(False)
        self.b_aut_3_2.setGeometry(QtCore.QRect(360, 430, 101, 31))
        self.b_aut_3_2.setObjectName("b_aut_3_2")

        self.l_img_3_3 = myLabel(self.centralwidget)
        self.l_img_3_3.setGeometry(QtCore.QRect(480, 320, 101, 101))
        self.l_img_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_3_3.setObjectName("l_img_3_3")
        self.l_aut_3_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_3_3.setEnabled(False)
        self.l_aut_3_3.setGeometry(QtCore.QRect(590, 320, 101, 101))
        self.l_aut_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_3_3.setObjectName("l_aut_3_3")
        self.b_buy_3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_3_3.setGeometry(QtCore.QRect(480, 430, 101, 31))
        self.b_buy_3_3.setObjectName("b_buy_3_3")
        self.b_aut_3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_3_3.setEnabled(False)
        self.b_aut_3_3.setGeometry(QtCore.QRect(590, 430, 101, 31))
        self.b_aut_3_3.setObjectName("b_aut_3_3")
                
        self.l_img_3_4 = myLabel(self.centralwidget)
        self.l_img_3_4.setGeometry(QtCore.QRect(710, 320, 101, 101))
        self.l_img_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_3_4.setObjectName("l_img_3_4")
        self.l_aut_3_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_3_4.setEnabled(False)
        self.l_aut_3_4.setGeometry(QtCore.QRect(820, 320, 101, 101))
        self.l_aut_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_3_4.setObjectName("l_aut_3_4")
        self.b_buy_3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_3_4.setGeometry(QtCore.QRect(710, 430, 101, 31))
        self.b_buy_3_4.setObjectName("b_buy_3_4")
        self.b_aut_3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_3_4.setEnabled(False)
        self.b_aut_3_4.setGeometry(QtCore.QRect(820, 430, 101, 31))
        self.b_aut_3_4.setObjectName("b_aut_3_4")

        self.l_img_3_5 = myLabel(self.centralwidget)
        self.l_img_3_5.setGeometry(QtCore.QRect(940, 320, 101, 101))
        self.l_img_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_3_5.setObjectName("l_img_3_5")
        self.l_aut_3_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_3_5.setEnabled(False)
        self.l_aut_3_5.setGeometry(QtCore.QRect(1050, 320, 101, 101))
        self.l_aut_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_3_5.setObjectName("l_aut_3_5")
        self.b_buy_3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_3_5.setGeometry(QtCore.QRect(940, 430, 101, 31))
        self.b_buy_3_5.setObjectName("b_buy_3_5")
        self.b_aut_3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_3_5.setEnabled(False)
        self.b_aut_3_5.setGeometry(QtCore.QRect(1050, 430, 101, 31))
        self.b_aut_3_5.setObjectName("b_aut_3_5")

        self.l_img_4_1 = myLabel(self.centralwidget)
        self.l_img_4_1.setGeometry(QtCore.QRect(20, 470, 101, 101))
        self.l_img_4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_4_1.setObjectName("l_img_4_1")
        self.l_aut_4_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_4_1.setEnabled(False)
        self.l_aut_4_1.setGeometry(QtCore.QRect(130, 470, 101, 101))
        self.l_aut_4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_4_1.setObjectName("l_aut_4_1")
        self.b_buy_4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_4_1.setGeometry(QtCore.QRect(20, 580, 101, 31))
        self.b_buy_4_1.setObjectName("b_buy_4_1")
        self.b_aut_4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_4_1.setEnabled(False)
        self.b_aut_4_1.setGeometry(QtCore.QRect(130, 580, 101, 31))
        self.b_aut_4_1.setObjectName("b_aut_4_1")
        
        self.l_img_4_2 = myLabel(self.centralwidget)
        self.l_img_4_2.setGeometry(QtCore.QRect(250, 470, 101, 101))
        self.l_img_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_4_2.setObjectName("l_img_4_2")
        self.l_aut_4_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_4_2.setEnabled(False)
        self.l_aut_4_2.setGeometry(QtCore.QRect(360, 470, 101, 101))
        self.l_aut_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_4_2.setObjectName("l_aut_4_2")
        self.b_buy_4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_4_2.setGeometry(QtCore.QRect(250, 580, 101, 31))
        self.b_buy_4_2.setObjectName("b_buy_4_2")
        self.b_aut_4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_4_2.setEnabled(False)
        self.b_aut_4_2.setGeometry(QtCore.QRect(360, 580, 101, 31))
        self.b_aut_4_2.setObjectName("b_aut_4_2")

        self.l_img_4_3 = myLabel(self.centralwidget)
        self.l_img_4_3.setGeometry(QtCore.QRect(480, 470, 101, 101))
        self.l_img_4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_4_3.setObjectName("l_img_4_3")
        self.l_aut_4_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_4_3.setEnabled(False)
        self.l_aut_4_3.setGeometry(QtCore.QRect(590, 470, 101, 101))
        self.l_aut_4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_4_3.setObjectName("l_aut_4_3")
        self.b_buy_4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_4_3.setGeometry(QtCore.QRect(480, 580, 101, 31))
        self.b_buy_4_3.setObjectName("b_buy_4_3")
        self.b_aut_4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_4_3.setEnabled(False)
        self.b_aut_4_3.setGeometry(QtCore.QRect(590, 580, 101, 31))
        self.b_aut_4_3.setObjectName("b_aut_4_3")
                
        self.l_img_4_4 = myLabel(self.centralwidget)
        self.l_img_4_4.setGeometry(QtCore.QRect(710, 470, 101, 101))
        self.l_img_4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_4_4.setObjectName("l_img_4_4")
        self.l_aut_4_4 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_4_4.setEnabled(False)
        self.l_aut_4_4.setGeometry(QtCore.QRect(820, 470, 101, 101))
        self.l_aut_4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_4_4.setObjectName("l_aut_4_4")
        self.b_buy_4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_4_4.setGeometry(QtCore.QRect(710, 580, 101, 31))
        self.b_buy_4_4.setObjectName("b_buy_4_4")
        self.b_aut_4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_4_4.setEnabled(False)
        self.b_aut_4_4.setGeometry(QtCore.QRect(820, 580, 101, 31))
        self.b_aut_4_4.setObjectName("b_aut_4_4")

        self.l_img_4_5 = myLabel(self.centralwidget)
        self.l_img_4_5.setGeometry(QtCore.QRect(940, 470, 101, 101))
        self.l_img_4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_img_4_5.setObjectName("l_img_4_5")
        self.l_aut_4_5 = QtWidgets.QLabel(self.centralwidget)
        self.l_aut_4_5.setEnabled(False)
        self.l_aut_4_5.setGeometry(QtCore.QRect(1050, 470, 101, 101))
        self.l_aut_4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.l_aut_4_5.setObjectName("l_aut_4_5")
        self.b_buy_4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_buy_4_5.setGeometry(QtCore.QRect(940, 580, 101, 31))
        self.b_buy_4_5.setObjectName("b_buy_4_5")
        self.b_aut_4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.b_aut_4_5.setEnabled(False)
        self.b_aut_4_5.setGeometry(QtCore.QRect(1050, 580, 101, 31))
        self.b_aut_4_5.setObjectName("b_aut_4_5")

        self.l_cost = QtWidgets.QLabel(self.centralwidget)
        self.l_cost.setGeometry(QtCore.QRect(50, 640, 300, 23))
        self.l_cost.setObjectName("l_cost")
        
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(550, 640, 75, 23))
        self.quit.setObjectName("quit")
        self.quit.clicked.connect(QtCore.QCoreApplication.instance().quit)
        
        self.b_buy_1_1.clicked.connect(self.showDialog_1_1)
        self.b_buy_1_2.clicked.connect(self.showDialog_1_2)
        self.b_buy_1_3.clicked.connect(self.showDialog_1_3)
        self.b_buy_1_4.clicked.connect(self.showDialog_1_4)
        self.b_buy_1_5.clicked.connect(self.showDialog_1_5)
        self.b_buy_2_1.clicked.connect(self.showDialog_2_1)
        self.b_buy_2_2.clicked.connect(self.showDialog_2_2)
        self.b_buy_2_3.clicked.connect(self.showDialog_2_3)
        self.b_buy_2_4.clicked.connect(self.showDialog_2_4)
        self.b_buy_2_5.clicked.connect(self.showDialog_2_5)
        self.b_buy_3_1.clicked.connect(self.showDialog_3_1)
        self.b_buy_3_2.clicked.connect(self.showDialog_3_2)
        self.b_buy_3_3.clicked.connect(self.showDialog_3_3)
        self.b_buy_3_4.clicked.connect(self.showDialog_3_4)
        self.b_buy_3_5.clicked.connect(self.showDialog_3_5)
        self.b_buy_4_1.clicked.connect(self.showDialog_4_1)
        self.b_buy_4_2.clicked.connect(self.showDialog_4_2)
        self.b_buy_4_3.clicked.connect(self.showDialog_4_3)
        self.b_buy_4_4.clicked.connect(self.showDialog_4_4)
        self.b_buy_4_5.clicked.connect(self.showDialog_4_5)

        self.b_aut_1_1.clicked.connect(self.authenticate_1_1)
        self.b_aut_1_2.clicked.connect(self.authenticate_1_2)
        self.b_aut_1_3.clicked.connect(self.authenticate_1_3)
        self.b_aut_1_4.clicked.connect(self.authenticate_1_4)
        self.b_aut_1_5.clicked.connect(self.authenticate_1_5)
        self.b_aut_2_1.clicked.connect(self.authenticate_2_1)
        self.b_aut_2_2.clicked.connect(self.authenticate_2_2)
        self.b_aut_2_3.clicked.connect(self.authenticate_2_3)
        self.b_aut_2_4.clicked.connect(self.authenticate_2_4)
        self.b_aut_2_5.clicked.connect(self.authenticate_2_5)
        self.b_aut_3_1.clicked.connect(self.authenticate_3_1)
        self.b_aut_3_2.clicked.connect(self.authenticate_3_2)
        self.b_aut_3_3.clicked.connect(self.authenticate_3_3)
        self.b_aut_3_4.clicked.connect(self.authenticate_3_4)
        self.b_aut_3_5.clicked.connect(self.authenticate_3_5)
        self.b_aut_4_1.clicked.connect(self.authenticate_4_1)
        self.b_aut_4_2.clicked.connect(self.authenticate_4_2)
        self.b_aut_4_3.clicked.connect(self.authenticate_4_3)
        self.b_aut_4_4.clicked.connect(self.authenticate_4_4)
        self.b_aut_4_5.clicked.connect(self.authenticate_4_5)

        MainWindow.setCentralWidget(self.centralwidget)

        self.cost = 0

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.l_img_1_1.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_1_1.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_1_1.setText(_translate("MainWindow", "购买"))
        self.b_aut_1_1.setText(_translate("MainWindow", "鉴定"))

        self.l_img_1_2.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_1_2.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_1_2.setText(_translate("MainWindow", "购买"))
        self.b_aut_1_2.setText(_translate("MainWindow", "鉴定"))

        self.l_img_1_3.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_1_3.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_1_3.setText(_translate("MainWindow", "购买"))
        self.b_aut_1_3.setText(_translate("MainWindow", "鉴定"))

        self.l_img_1_4.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_1_4.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_1_4.setText(_translate("MainWindow", "购买"))
        self.b_aut_1_4.setText(_translate("MainWindow", "鉴定"))

        self.l_img_1_5.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_1_5.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_1_5.setText(_translate("MainWindow", "购买"))
        self.b_aut_1_5.setText(_translate("MainWindow", "鉴定"))

        self.l_img_2_1.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_2_1.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_2_1.setText(_translate("MainWindow", "购买"))
        self.b_aut_2_1.setText(_translate("MainWindow", "鉴定"))

        self.l_img_2_2.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_2_2.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_2_2.setText(_translate("MainWindow", "购买"))
        self.b_aut_2_2.setText(_translate("MainWindow", "鉴定"))

        self.l_img_2_3.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_2_3.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_2_3.setText(_translate("MainWindow", "购买"))
        self.b_aut_2_3.setText(_translate("MainWindow", "鉴定"))

        self.l_img_2_4.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_2_4.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_2_4.setText(_translate("MainWindow", "购买"))
        self.b_aut_2_4.setText(_translate("MainWindow", "鉴定"))

        self.l_img_2_5.setText(_translate("MainWindow", "点击购买"))
        self.b_buy_2_5.setText(_translate("MainWindow", "购买"))
        self.b_aut_2_5.setText(_translate("MainWindow", "鉴定"))
        self.l_aut_2_5.setText(_translate("MainWindow", "点击鉴定"))
        
        self.l_img_3_1.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_3_1.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_3_1.setText(_translate("MainWindow", "购买"))
        self.b_aut_3_1.setText(_translate("MainWindow", "鉴定"))

        self.l_img_3_2.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_3_2.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_3_2.setText(_translate("MainWindow", "购买"))
        self.b_aut_3_2.setText(_translate("MainWindow", "鉴定"))
        
        self.l_img_3_3.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_3_3.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_3_3.setText(_translate("MainWindow", "购买"))
        self.b_aut_3_3.setText(_translate("MainWindow", "鉴定"))

        self.l_img_3_4.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_3_4.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_3_4.setText(_translate("MainWindow", "购买"))
        self.b_aut_3_4.setText(_translate("MainWindow", "鉴定"))

        self.l_img_3_5.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_3_5.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_3_5.setText(_translate("MainWindow", "购买"))
        self.b_aut_3_5.setText(_translate("MainWindow", "鉴定"))

        self.l_img_4_1.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_4_1.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_4_1.setText(_translate("MainWindow", "购买"))
        self.b_aut_4_1.setText(_translate("MainWindow", "鉴定"))
        
        self.l_img_4_2.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_4_2.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_4_2.setText(_translate("MainWindow", "购买"))
        self.b_aut_4_2.setText(_translate("MainWindow", "鉴定"))

        self.l_img_4_3.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_4_3.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_4_3.setText(_translate("MainWindow", "购买"))
        self.b_aut_4_3.setText(_translate("MainWindow", "鉴定"))
        
        self.l_img_4_4.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_4_4.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_4_4.setText(_translate("MainWindow", "购买"))
        self.b_aut_4_4.setText(_translate("MainWindow", "鉴定"))
        
        self.l_img_4_5.setText(_translate("MainWindow", "点击购买"))
        self.l_aut_4_5.setText(_translate("MainWindow", "点击鉴定"))
        self.b_buy_4_5.setText(_translate("MainWindow", "购买"))
        self.b_aut_4_5.setText(_translate("MainWindow", "鉴定"))

        self.l_cost.setText(_translate("MainWindow", f"总成本: {self.cost}元"))

        self.quit.setText(_translate("MainWindow", "退出"))
        
    def showDialog_1_1(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_1_1.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_1_1.setInfo(type, level)
            self.l_aut_1_1.setEnabled(True)
            self.l_aut_1_1.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_1_1.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_1_1.setEnabled(True)
    
    def showDialog_1_2(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_1_2.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_1_2.setInfo(type, level)
            self.l_aut_1_2.setEnabled(True)
            self.l_aut_1_2.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_1_2.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_1_2.setEnabled(True)
    
    def showDialog_1_3(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_1_3.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_1_3.setInfo(type, level)
            self.l_aut_1_3.setEnabled(True)
            self.l_aut_1_3.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_1_3.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_1_3.setEnabled(True)
    
    def showDialog_1_4(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_1_4.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_1_4.setInfo(type, level)
            self.l_aut_1_4.setEnabled(True)
            self.l_aut_1_4.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_1_4.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_1_4.setEnabled(True)
    
    def showDialog_1_5(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_1_5.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_1_5.setInfo(type, level)
            self.l_aut_1_5.setEnabled(True)
            self.l_aut_1_5.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_1_5.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_1_5.setEnabled(True)

    def showDialog_2_1(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_2_1.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_2_1.setInfo(type, level)
            self.l_aut_2_1.setEnabled(True)
            self.l_aut_2_1.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_2_1.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_2_1.setEnabled(True)
    
    def showDialog_2_2(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_2_2.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_2_2.setInfo(type, level)
            self.l_aut_2_2.setEnabled(True)
            self.l_aut_2_2.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_2_2.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_2_2.setEnabled(True)
    
    def showDialog_2_3(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_2_3.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_2_3.setInfo(type, level)
            self.l_aut_2_3.setEnabled(True)
            self.l_aut_2_3.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_2_3.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_2_3.setEnabled(True)
    
    def showDialog_2_4(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_2_4.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_2_4.setInfo(type, level)
            self.l_aut_2_4.setEnabled(True)
            self.l_aut_2_4.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_2_4.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_2_4.setEnabled(True)
    
    def showDialog_2_5(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_2_5.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_2_5.setInfo(type, level)
            self.l_aut_2_5.setEnabled(True)
            self.l_aut_2_5.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_2_5.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_2_5.setEnabled(True)

    def showDialog_3_1(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_3_1.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_3_1.setInfo(type, level)
            self.l_aut_3_1.setEnabled(True)
            self.l_aut_3_1.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_3_1.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_3_1.setEnabled(True)
    
    def showDialog_3_2(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_3_2.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_3_2.setInfo(type, level)
            self.l_aut_3_2.setEnabled(True)
            self.l_aut_3_2.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_3_2.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_3_2.setEnabled(True)
    
    def showDialog_3_3(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_3_3.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_3_3.setInfo(type, level)
            self.l_aut_3_3.setEnabled(True)
            self.l_aut_3_3.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_3_3.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_3_3.setEnabled(True)
    
    def showDialog_3_4(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_3_4.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_3_4.setInfo(type, level)
            self.l_aut_3_4.setEnabled(True)
            self.l_aut_3_4.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_3_4.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_3_4.setEnabled(True)
    
    def showDialog_3_5(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_3_5.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_3_5.setInfo(type, level)
            self.l_aut_3_5.setEnabled(True)
            self.l_aut_3_5.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_3_5.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_3_5.setEnabled(True)

    def showDialog_4_1(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_4_1.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_4_1.setInfo(type, level)
            self.l_aut_4_1.setEnabled(True)
            self.l_aut_4_1.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_4_1.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_4_1.setEnabled(True)
    
    def showDialog_4_2(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_4_2.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_4_2.setInfo(type, level)
            self.l_aut_4_2.setEnabled(True)
            self.l_aut_4_2.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_4_2.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_4_2.setEnabled(True)
    
    def showDialog_4_3(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_4_3.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_4_3.setInfo(type, level)
            self.l_aut_4_3.setEnabled(True)
            self.l_aut_4_3.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_4_3.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_4_3.setEnabled(True)
    
    def showDialog_4_4(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_4_4.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_4_4.setInfo(type, level)
            self.l_aut_4_4.setEnabled(True)
            self.l_aut_4_4.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_4_4.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_4_4.setEnabled(True)
    
    def showDialog_4_5(self):
        dialog = myDialog()
        ui = Ui_Dialog()
        ui.setupUi(dialog)
        dialog.setWindowTitle('杂货摊位')
        dialog.setWindowIcon(QtGui.QIcon('img/logo.ico'))
        dialog.show()
        dialog.exec_()
        type_id, type, level, cost = dialog.getInfo()
        if type is not None:
            self.cost += cost
            self.l_cost.setText(QtCore.QCoreApplication.translate("MainWindow", f"总成本: {self.cost}元"))
            self.l_img_4_5.setPixmap(QtGui.QPixmap(f"img/xyq_gifs/27{type_id}0{level//20-2}.gif").scaled(100, 100))
            self.l_img_4_5.setInfo(type, level)
            self.l_aut_4_5.setEnabled(True)
            self.l_aut_4_5.setAlignment(QtCore.Qt.AlignLeft)
            self.l_aut_4_5.setText(QtCore.QCoreApplication.translate("MainWindow", f"{NAME_DIC[type][level]}\n{NAME[type]} 等级：{level}\n未鉴定灵饰"))
            self.b_aut_4_5.setEnabled(True)

    def authenticate_1_1(self):
        aut_str = self.l_img_1_1.getInfo()
        self.l_aut_1_1.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_1_1.setEnabled(False)

    def authenticate_1_2(self):
        aut_str = self.l_img_1_2.getInfo()
        self.l_aut_1_2.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_1_2.setEnabled(False)

    def authenticate_1_3(self):
        aut_str = self.l_img_1_3.getInfo()
        self.l_aut_1_3.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_1_3.setEnabled(False)

    def authenticate_1_4(self):
        aut_str = self.l_img_1_4.getInfo()
        self.l_aut_1_4.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_1_4.setEnabled(False)

    def authenticate_1_5(self):
        aut_str = self.l_img_1_5.getInfo()
        self.l_aut_1_5.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_1_5.setEnabled(False)

    def authenticate_2_1(self):
        aut_str = self.l_img_2_1.getInfo()
        self.l_aut_2_1.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_2_1.setEnabled(False)

    def authenticate_2_2(self):
        aut_str = self.l_img_2_2.getInfo()
        self.l_aut_2_2.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_2_2.setEnabled(False)

    def authenticate_2_3(self):
        aut_str = self.l_img_2_3.getInfo()
        self.l_aut_2_3.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_2_3.setEnabled(False)

    def authenticate_2_4(self):
        aut_str = self.l_img_2_4.getInfo()
        self.l_aut_2_4.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_2_4.setEnabled(False)

    def authenticate_2_5(self):
        aut_str = self.l_img_2_5.getInfo()
        self.l_aut_2_5.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_2_5.setEnabled(False)

    def authenticate_3_1(self):
        aut_str = self.l_img_3_1.getInfo()
        self.l_aut_3_1.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_3_1.setEnabled(False)

    def authenticate_3_2(self):
        aut_str = self.l_img_3_2.getInfo()
        self.l_aut_3_2.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_3_2.setEnabled(False)

    def authenticate_3_3(self):
        aut_str = self.l_img_3_3.getInfo()
        self.l_aut_3_3.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_3_3.setEnabled(False)

    def authenticate_3_4(self):
        aut_str = self.l_img_3_4.getInfo()
        self.l_aut_3_4.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_3_4.setEnabled(False)

    def authenticate_3_5(self):
        aut_str = self.l_img_3_5.getInfo()
        self.l_aut_3_5.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_3_5.setEnabled(False)

    def authenticate_4_1(self):
        aut_str = self.l_img_4_1.getInfo()
        self.l_aut_4_1.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_4_1.setEnabled(False)

    def authenticate_4_2(self):
        aut_str = self.l_img_4_2.getInfo()
        self.l_aut_4_2.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_4_2.setEnabled(False)

    def authenticate_4_3(self):
        aut_str = self.l_img_4_3.getInfo()
        self.l_aut_4_3.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_4_3.setEnabled(False)

    def authenticate_4_4(self):
        aut_str = self.l_img_4_4.getInfo()
        self.l_aut_4_4.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_4_4.setEnabled(False)

    def authenticate_4_5(self):
        aut_str = self.l_img_4_5.getInfo()
        self.l_aut_4_5.setText(QtCore.QCoreApplication.translate("MainWindow", aut_str))
        self.b_aut_4_5.setEnabled(False)
