# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\code\python\Authenticate\select.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(742, 668)

        self.l_img_1_1 = QtWidgets.QLabel(Dialog)
        self.l_img_1_1.setGeometry(QtCore.QRect(20, 20, 101, 101))
        self.l_img_1_1.setText("")
        self.l_img_1_1.setPixmap(QtGui.QPixmap("img/png_100/ring_60.png"))
        self.l_img_1_1.setObjectName("l_img_1_1")
        self.b_buy_1_1 = QtWidgets.QPushButton(Dialog)
        self.b_buy_1_1.setGeometry(QtCore.QRect(20, 130, 101, 23))
        self.b_buy_1_1.setObjectName("b_buy_1_1")

        self.l_img_1_2 = QtWidgets.QLabel(Dialog)
        self.l_img_1_2.setGeometry(QtCore.QRect(140, 20, 101, 101))
        self.l_img_1_2.setText("")
        self.l_img_1_2.setPixmap(QtGui.QPixmap("img/png_100/ring_80.png"))
        self.l_img_1_2.setObjectName("l_img_1_2")
        self.b_buy_1_2 = QtWidgets.QPushButton(Dialog)
        self.b_buy_1_2.setGeometry(QtCore.QRect(140, 130, 101, 23))
        self.b_buy_1_2.setObjectName("b_buy_1_2")
        
        self.l_img_1_3 = QtWidgets.QLabel(Dialog)
        self.l_img_1_3.setGeometry(QtCore.QRect(260, 20, 101, 101))
        self.l_img_1_3.setText("")
        self.l_img_1_3.setPixmap(QtGui.QPixmap("img/png_100/ring_100.png"))
        self.l_img_1_3.setObjectName("l_img_1_3")
        self.b_buy_1_3 = QtWidgets.QPushButton(Dialog)
        self.b_buy_1_3.setGeometry(QtCore.QRect(260, 130, 101, 23))
        self.b_buy_1_3.setObjectName("b_buy_1_3")

        self.l_img_1_4 = QtWidgets.QLabel(Dialog)
        self.l_img_1_4.setGeometry(QtCore.QRect(380, 20, 101, 101))
        self.l_img_1_4.setText("")
        self.l_img_1_4.setPixmap(QtGui.QPixmap("img/png_100/ring_120.png"))
        self.l_img_1_4.setObjectName("l_img_1_4")
        self.b_buy_1_4 = QtWidgets.QPushButton(Dialog)
        self.b_buy_1_4.setGeometry(QtCore.QRect(380, 130, 101, 23))
        self.b_buy_1_4.setObjectName("b_buy_1_4")

        self.l_img_1_5 = QtWidgets.QLabel(Dialog)
        self.l_img_1_5.setGeometry(QtCore.QRect(500, 20, 101, 101))
        self.l_img_1_5.setText("")
        self.l_img_1_5.setPixmap(QtGui.QPixmap("img/png_100/ring_140.png"))
        self.l_img_1_5.setObjectName("l_img_1_5")
        self.b_buy_1_5 = QtWidgets.QPushButton(Dialog)
        self.b_buy_1_5.setGeometry(QtCore.QRect(500, 130, 101, 23))
        self.b_buy_1_5.setObjectName("b_buy_1_5")

        self.l_img_1_6 = QtWidgets.QLabel(Dialog)
        self.l_img_1_6.setGeometry(QtCore.QRect(620, 20, 101, 101))
        self.l_img_1_6.setText("")
        self.l_img_1_6.setPixmap(QtGui.QPixmap("img/png_100/ring_160.png"))
        self.l_img_1_6.setObjectName("l_img_1_6")
        self.b_buy_1_6 = QtWidgets.QPushButton(Dialog)
        self.b_buy_1_6.setGeometry(QtCore.QRect(620, 130, 101, 23))
        self.b_buy_1_6.setObjectName("b_buy_1_6")
        
        self.l_img_2_1 = QtWidgets.QLabel(Dialog)
        self.l_img_2_1.setGeometry(QtCore.QRect(20, 170, 101, 101))
        self.l_img_2_1.setText("")
        self.l_img_2_1.setPixmap(QtGui.QPixmap("img/png_100/earring_60.png"))
        self.l_img_2_1.setObjectName("l_img_2_1")
        self.b_buy_2_1 = QtWidgets.QPushButton(Dialog)
        self.b_buy_2_1.setGeometry(QtCore.QRect(20, 280, 101, 23))
        self.b_buy_2_1.setObjectName("b_buy_2_1")

        self.l_img_2_2 = QtWidgets.QLabel(Dialog)
        self.l_img_2_2.setGeometry(QtCore.QRect(140, 170, 101, 101))
        self.l_img_2_2.setText("")
        self.l_img_2_2.setPixmap(QtGui.QPixmap("img/png_100/earring_80.png"))
        self.l_img_2_2.setObjectName("l_img_2_2")
        self.b_buy_2_2 = QtWidgets.QPushButton(Dialog)
        self.b_buy_2_2.setGeometry(QtCore.QRect(140, 280, 101, 23))
        self.b_buy_2_2.setObjectName("b_buy_2_2")

        self.l_img_2_3 = QtWidgets.QLabel(Dialog)
        self.l_img_2_3.setGeometry(QtCore.QRect(260, 170, 101, 101))
        self.l_img_2_3.setText("")
        self.l_img_2_3.setPixmap(QtGui.QPixmap("img/png_100/earring_100.png"))
        self.l_img_2_3.setObjectName("l_img_2_3")
        self.b_buy_2_3 = QtWidgets.QPushButton(Dialog)
        self.b_buy_2_3.setGeometry(QtCore.QRect(260, 280, 101, 23))
        self.b_buy_2_3.setObjectName("b_buy_2_3")

        self.l_img_2_4 = QtWidgets.QLabel(Dialog)
        self.l_img_2_4.setGeometry(QtCore.QRect(380, 170, 101, 101))
        self.l_img_2_4.setText("")
        self.l_img_2_4.setPixmap(QtGui.QPixmap("img/png_100/earring_120.png"))
        self.l_img_2_4.setObjectName("l_img_2_4")
        self.b_buy_2_4 = QtWidgets.QPushButton(Dialog)
        self.b_buy_2_4.setGeometry(QtCore.QRect(380, 280, 101, 23))
        self.b_buy_2_4.setObjectName("b_buy_2_4")

        self.l_img_2_5 = QtWidgets.QLabel(Dialog)
        self.l_img_2_5.setGeometry(QtCore.QRect(500, 170, 101, 101))
        self.l_img_2_5.setText("")
        self.l_img_2_5.setPixmap(QtGui.QPixmap("img/png_100/earring_140.png"))
        self.l_img_2_5.setObjectName("l_img_2_5")
        self.b_buy_2_5 = QtWidgets.QPushButton(Dialog)
        self.b_buy_2_5.setGeometry(QtCore.QRect(500, 280, 101, 23))
        self.b_buy_2_5.setObjectName("b_buy_2_5")

        self.l_img_2_6 = QtWidgets.QLabel(Dialog)
        self.l_img_2_6.setGeometry(QtCore.QRect(620, 170, 101, 101))
        self.l_img_2_6.setText("")
        self.l_img_2_6.setPixmap(QtGui.QPixmap("img/png_100/earring_160.png"))
        self.l_img_2_6.setObjectName("l_img_2_6")
        self.b_buy_2_6 = QtWidgets.QPushButton(Dialog)
        self.b_buy_2_6.setGeometry(QtCore.QRect(620, 280, 101, 23))
        self.b_buy_2_6.setObjectName("b_buy_2_6")
        
        self.l_img_3_1 = QtWidgets.QLabel(Dialog)
        self.l_img_3_1.setGeometry(QtCore.QRect(20, 320, 101, 101))
        self.l_img_3_1.setText("")
        self.l_img_3_1.setPixmap(QtGui.QPixmap("img/png_100/accessory_60.png"))
        self.l_img_3_1.setObjectName("l_img_3_1")
        self.b_buy_3_1 = QtWidgets.QPushButton(Dialog)
        self.b_buy_3_1.setGeometry(QtCore.QRect(20, 430, 101, 23))
        self.b_buy_3_1.setObjectName("b_buy_3_1")

        self.l_img_3_2 = QtWidgets.QLabel(Dialog)
        self.l_img_3_2.setGeometry(QtCore.QRect(140, 320, 101, 101))
        self.l_img_3_2.setText("")
        self.l_img_3_2.setPixmap(QtGui.QPixmap("img/png_100/accessory_80.png"))
        self.l_img_3_2.setObjectName("l_img_3_2")
        self.b_buy_3_2 = QtWidgets.QPushButton(Dialog)
        self.b_buy_3_2.setGeometry(QtCore.QRect(140, 430, 101, 23))
        self.b_buy_3_2.setObjectName("b_buy_3_2")
        
        self.l_img_3_3 = QtWidgets.QLabel(Dialog)
        self.l_img_3_3.setGeometry(QtCore.QRect(260, 320, 101, 101))
        self.l_img_3_3.setText("")
        self.l_img_3_3.setPixmap(QtGui.QPixmap("img/png_100/accessory_100.png"))
        self.l_img_3_3.setObjectName("l_img_3_3")
        self.b_buy_3_3 = QtWidgets.QPushButton(Dialog)
        self.b_buy_3_3.setGeometry(QtCore.QRect(260, 430, 101, 23))
        self.b_buy_3_3.setObjectName("b_buy_3_3")

        self.l_img_3_4 = QtWidgets.QLabel(Dialog)
        self.l_img_3_4.setGeometry(QtCore.QRect(380, 320, 101, 101))
        self.l_img_3_4.setText("")
        self.l_img_3_4.setPixmap(QtGui.QPixmap("img/png_100/accessory_120.png"))
        self.l_img_3_4.setObjectName("l_img_3_4")
        self.b_buy_3_4 = QtWidgets.QPushButton(Dialog)
        self.b_buy_3_4.setGeometry(QtCore.QRect(380, 430, 101, 23))
        self.b_buy_3_4.setObjectName("b_buy_3_4")

        self.l_img_3_5 = QtWidgets.QLabel(Dialog)
        self.l_img_3_5.setGeometry(QtCore.QRect(500, 320, 101, 101))
        self.l_img_3_5.setText("")
        self.l_img_3_5.setPixmap(QtGui.QPixmap("img/png_100/accessory_140.png"))
        self.l_img_3_5.setObjectName("l_img_3_5")
        self.b_buy_3_5 = QtWidgets.QPushButton(Dialog)
        self.b_buy_3_5.setGeometry(QtCore.QRect(500, 430, 101, 23))
        self.b_buy_3_5.setObjectName("b_buy_3_5")

        self.l_img_3_6 = QtWidgets.QLabel(Dialog)
        self.l_img_3_6.setGeometry(QtCore.QRect(620, 320, 101, 101))
        self.l_img_3_6.setText("")
        self.l_img_3_6.setPixmap(QtGui.QPixmap("img/png_100/accessory_160.png"))
        self.l_img_3_6.setObjectName("l_img_3_6")
        self.b_buy_3_6 = QtWidgets.QPushButton(Dialog)
        self.b_buy_3_6.setGeometry(QtCore.QRect(620, 430, 101, 23))
        self.b_buy_3_6.setObjectName("b_buy_3_6")
        
        self.l_img_4_1 = QtWidgets.QLabel(Dialog)
        self.l_img_4_1.setGeometry(QtCore.QRect(20, 470, 101, 101))
        self.l_img_4_1.setText("")
        self.l_img_4_1.setPixmap(QtGui.QPixmap("img/png_100/bracelet_60.png"))
        self.l_img_4_1.setObjectName("l_img_4_1")
        self.b_buy_4_1 = QtWidgets.QPushButton(Dialog)
        self.b_buy_4_1.setGeometry(QtCore.QRect(20, 580, 101, 23))
        self.b_buy_4_1.setObjectName("b_buy_4_1")

        self.l_img_4_2 = QtWidgets.QLabel(Dialog)
        self.l_img_4_2.setGeometry(QtCore.QRect(140, 470, 101, 101))
        self.l_img_4_2.setText("")
        self.l_img_4_2.setPixmap(QtGui.QPixmap("img/png_100/bracelet_80.png"))
        self.l_img_4_2.setObjectName("l_img_4_2")
        self.b_buy_4_2 = QtWidgets.QPushButton(Dialog)
        self.b_buy_4_2.setGeometry(QtCore.QRect(140, 580, 101, 23))
        self.b_buy_4_2.setObjectName("b_buy_4_2")

        self.l_img_4_3 = QtWidgets.QLabel(Dialog)
        self.l_img_4_3.setGeometry(QtCore.QRect(260, 470, 101, 101))
        self.l_img_4_3.setText("")
        self.l_img_4_3.setPixmap(QtGui.QPixmap("img/png_100/bracelet_100.png"))
        self.l_img_4_3.setObjectName("l_img_4_3")
        self.b_buy_4_3 = QtWidgets.QPushButton(Dialog)
        self.b_buy_4_3.setGeometry(QtCore.QRect(260, 580, 101, 23))
        self.b_buy_4_3.setObjectName("b_buy_4_3")

        self.l_img_4_4 = QtWidgets.QLabel(Dialog)
        self.l_img_4_4.setGeometry(QtCore.QRect(380, 470, 101, 101))
        self.l_img_4_4.setText("")
        self.l_img_4_4.setPixmap(QtGui.QPixmap("img/png_100/bracelet_120.png"))
        self.l_img_4_4.setObjectName("l_img_4_4")
        self.b_buy_4_4 = QtWidgets.QPushButton(Dialog)
        self.b_buy_4_4.setGeometry(QtCore.QRect(380, 580, 101, 23))
        self.b_buy_4_4.setObjectName("b_buy_4_4")

        self.l_img_4_5 = QtWidgets.QLabel(Dialog)
        self.l_img_4_5.setGeometry(QtCore.QRect(500, 470, 101, 101))
        self.l_img_4_5.setText("")
        self.l_img_4_5.setPixmap(QtGui.QPixmap("img/png_100/bracelet_140.png"))
        self.l_img_4_5.setObjectName("l_img_4_5")
        self.b_buy_4_5 = QtWidgets.QPushButton(Dialog)
        self.b_buy_4_5.setGeometry(QtCore.QRect(500, 580, 101, 23))
        self.b_buy_4_5.setObjectName("b_buy_4_5")

        self.l_img_4_6 = QtWidgets.QLabel(Dialog)
        self.l_img_4_6.setGeometry(QtCore.QRect(620, 470, 101, 101))
        self.l_img_4_6.setText("")
        self.l_img_4_6.setPixmap(QtGui.QPixmap("img/png_100/bracelet_160.png"))
        self.l_img_4_6.setObjectName("l_img_4_6")
        self.b_buy_4_6 = QtWidgets.QPushButton(Dialog)
        self.b_buy_4_6.setGeometry(QtCore.QRect(620, 580, 101, 23))
        self.b_buy_4_6.setObjectName("b_buy_4_6")
        
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(330, 630, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(Dialog.close)

        self.b_buy_1_1.clicked.connect(lambda: Dialog.setInfo(1, 1))
        self.b_buy_1_2.clicked.connect(lambda: Dialog.setInfo(1, 2))
        self.b_buy_1_3.clicked.connect(lambda: Dialog.setInfo(1, 3))
        self.b_buy_1_4.clicked.connect(lambda: Dialog.setInfo(1, 4))
        self.b_buy_1_5.clicked.connect(lambda: Dialog.setInfo(1, 5))
        self.b_buy_1_6.clicked.connect(lambda: Dialog.setInfo(1, 6))
        self.b_buy_2_1.clicked.connect(lambda: Dialog.setInfo(2, 1))
        self.b_buy_2_2.clicked.connect(lambda: Dialog.setInfo(2, 2))
        self.b_buy_2_3.clicked.connect(lambda: Dialog.setInfo(2, 3))
        self.b_buy_2_4.clicked.connect(lambda: Dialog.setInfo(2, 4))
        self.b_buy_2_5.clicked.connect(lambda: Dialog.setInfo(2, 5))
        self.b_buy_2_6.clicked.connect(lambda: Dialog.setInfo(2, 6))
        self.b_buy_3_1.clicked.connect(lambda: Dialog.setInfo(3, 1))
        self.b_buy_3_2.clicked.connect(lambda: Dialog.setInfo(3, 2))
        self.b_buy_3_3.clicked.connect(lambda: Dialog.setInfo(3, 3))
        self.b_buy_3_4.clicked.connect(lambda: Dialog.setInfo(3, 4))
        self.b_buy_3_5.clicked.connect(lambda: Dialog.setInfo(3, 5))
        self.b_buy_3_6.clicked.connect(lambda: Dialog.setInfo(3, 6))
        self.b_buy_4_1.clicked.connect(lambda: Dialog.setInfo(4, 1))
        self.b_buy_4_2.clicked.connect(lambda: Dialog.setInfo(4, 2))
        self.b_buy_4_3.clicked.connect(lambda: Dialog.setInfo(4, 3))
        self.b_buy_4_4.clicked.connect(lambda: Dialog.setInfo(4, 4))
        self.b_buy_4_5.clicked.connect(lambda: Dialog.setInfo(4, 5))
        self.b_buy_4_6.clicked.connect(lambda: Dialog.setInfo(4, 6))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.l_img_1_1.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">枫华戒</span></p><p>戒指</p><p>等级：60</p></body></html>"))
        self.b_buy_1_1.setText(_translate("Dialog", "选择"))
        self.b_buy_2_1.setText(_translate("Dialog", "选择"))
        self.l_img_2_1.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">翠叶环</span></p><p>耳饰</p><p>等级：60</p></body></html>"))
        self.l_img_3_1.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">芝兰佩</span></p><p>配饰</p><p>等级：60</p></body></html>"))
        self.b_buy_3_1.setText(_translate("Dialog", "选择"))
        self.b_buy_4_1.setText(_translate("Dialog", "选择"))
        self.l_img_4_1.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">香木镯</span></p><p>手镯</p><p>等级：60</p></body></html>"))
        self.l_img_3_2.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">逸云佩</span></p><p>配饰</p><p>等级：80</p></body></html>"))
        self.b_buy_3_2.setText(_translate("Dialog", "选择"))
        self.b_buy_4_2.setText(_translate("Dialog", "选择"))
        self.l_img_4_2.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">翡玉镯</span></p><p>手镯</p><p>等级：80</p></body></html>"))
        self.l_img_1_2.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">芙蓉戒</span></p><p>戒指</p><p>等级：80</p></body></html>"))
        self.b_buy_2_2.setText(_translate("Dialog", "选择"))
        self.l_img_2_2.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">明月珰</span></p><p>耳饰</p><p>等级：80</p></body></html>"))
        self.b_buy_1_2.setText(_translate("Dialog", "选择"))
        self.l_img_3_3.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">莲音玦</span></p><p>配饰</p><p>等级：100</p></body></html>"))
        self.b_buy_3_3.setText(_translate("Dialog", "选择"))
        self.b_buy_4_3.setText(_translate("Dialog", "选择"))
        self.b_buy_2_3.setText(_translate("Dialog", "选择"))
        self.l_img_4_3.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">墨影扣</span></p><p>手镯</p><p>等级：100</p></body></html>"))
        self.l_img_2_3.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">玉蝶翩</span></p><p>耳饰</p><p>等级：100</p></body></html>"))
        self.l_img_1_3.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">金鳞绕</span></p><p>戒指</p><p>等级：100</p></body></html>"))
        self.l_img_1_4.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">悦碧水</span></p><p>戒指</p><p>等级：120</p></body></html>"))
        self.b_buy_2_4.setText(_translate("Dialog", "选择"))
        self.l_img_3_4.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">相思染</span></p><p>配饰</p><p>等级：120</p></body></html>"))
        self.l_img_4_4.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">花映月</span></p><p>手镯</p><p>等级：120</p></body></html>"))
        self.b_buy_3_4.setText(_translate("Dialog", "选择"))
        self.b_buy_1_3.setText(_translate("Dialog", "选择"))
        self.l_img_2_4.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">点星芒</span></p><p>耳饰</p><p>等级：120</p></body></html>"))
        self.b_buy_4_4.setText(_translate("Dialog", "选择"))
        self.b_buy_1_4.setText(_translate("Dialog", "选择"))
        self.l_img_3_5.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">玄龙苍珀</span></p><p>配饰</p><p>等级：140</p></body></html>"))
        self.b_buy_3_5.setText(_translate("Dialog", "选择"))
        self.b_buy_4_5.setText(_translate("Dialog", "选择"))
        self.b_buy_2_5.setText(_translate("Dialog", "选择"))
        self.l_img_4_5.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">金水菩提</span></p><p>手镯</p><p>等级：140</p></body></html>"))
        self.l_img_2_5.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">凤羽流苏</span></p><p>耳饰</p><p>等级：140</p></body></html>"))
        self.l_img_1_5.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">九曜光华</span></p><p>戒指</p><p>等级：140</p></body></html>"))
        self.l_img_1_6.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">太虚渺云</span></p><p>戒指</p><p>等级：160</p></body></html>"))
        self.b_buy_2_6.setText(_translate("Dialog", "选择"))
        self.l_img_3_6.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">碧海青天</span></p><p>配饰</p><p>等级：160</p></body></html>"))
        self.l_img_4_6.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">浮雪幻音</span></p><p>手镯</p><p>等级：160</p></body></html>"))
        self.b_buy_3_6.setText(_translate("Dialog", "选择"))
        self.b_buy_1_5.setText(_translate("Dialog", "选择"))
        self.l_img_2_6.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">焰云霞珠</span></p><p>耳饰</p><p>等级：160</p></body></html>"))
        self.b_buy_4_6.setText(_translate("Dialog", "选择"))
        self.b_buy_1_6.setText(_translate("Dialog", "选择"))
        self.pushButton.setText(_translate("Dialog", "确定"))
